name: Release

on:
  push:
    tags:
      - 'main'
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: GOOS=${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }} GOARCH=amd64 go build -o hyperops_${{ matrix.os == 'windows-latest' && 'windows.exe' || 'linux' }} .
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: ./hyperops_${{ matrix.os == 'windows-latest' && 'windows.exe' || 'linux' }}
          asset_name: hyperops_${{ matrix.os == 'windows-latest' && 'windows.exe' || 'linux' }}
          asset_content_type: application/octet-stream
